from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from database import Base
from datetime import datetime

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    whatsapp_number = Column(String, unique=True, index=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # One User can have multiple ROIs
    rois = relationship("RegionOfInterest", back_populates="owner")

class RegionOfInterest(Base):
    __tablename__ = "rois"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)  # e.g., "Mumbai Coastline"
    wkt_polygon = Column(String)       # The exact string generated by Leaflet map
    is_monitoring = Column(Boolean, default=True)
    owner_id = Column(Integer, ForeignKey("users.id"))
    
    owner = relationship("User", back_populates="rois")